diary/urls.py
from django.urls import path, re_path

from . import views

app_name = "diary"
urlpatterns = [
    path("<int:job_id>/", views.detail, name="detail"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("", views.JobListView.as_view(), name="joblist"),
]

diary/models.py
from datetime import datetime, date
import logging

from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import get_user_model
from django.db import models, IntegrityError
from django.db.models import Q
from django.utils.dateparse import parse_datetime
from django.utils import timezone

from utils.email import get_name_from_email
from utils.project import get_project_from_path


class Keyword(models.Model):
    """
    Simple model to store keywords to aid search for a Job
    """
    word = models.CharField(
        unique=True,
        max_length=200,
        db_index=True
    )

    def __str__(self):
        return self.word


class JobQuerySet(models.QuerySet):
    """
    Defines additional methods that can applied on Job querysets.
    """
    logger = logging.getLogger(__name__)

    def keyword_search(self, search_query):
        """
        Get QuerySet of Jobs for which all words of the search query are
        found in the keyword associations.

        If the search is conducted for an empty search term, no results
        should be presented. This is not a filter. It is a search.
        It might act like a filter most of the time, but this is the
        difference. If you search for nothing you will find nothing.
        If you search for something, you till find something, given that it
        can be found/exists.
        """
        self.logger.debug("Search query: {}".format(search_query))
        if search_query.strip():
            for word in search_query.split():
                self = self.filter(keywords__word__istartswith=word).distinct()
        else:
            self = self.none()
        return self


class Job(models.Model):
    logger = logging.getLogger(__name__).getChild("Job")

    objects = JobQuerySet.as_manager()

    job_id = models.PositiveIntegerField(primary_key=True)

    main_name = models.CharField(
        max_length=200,
        blank=False,
    )

    @property
    def _keyword_parsed_main_name(self):
        """
        Return string of the parsed `main_name` of the job

        The returned string should only contain whitespace separated words
        that are considered useful e.g. to search for this job.
        """
        # Remove last dot
        # Inspired by https://stackoverflow.com/a/2556252
        split_at_last_dot = str(self.main_name).rsplit(".", 1)
        last_dot_replaced = " ".join(split_at_last_dot)
        stripped_underscore = last_dot_replaced.replace("_", " ")
        return stripped_underscore

    JOB_STATUS_NONE = "non"
    JOB_STATUS_PENDING = "pen"
    JOB_STATUS_RUNNING = "run"
    JOB_STATUS_FINISHED = "fin"
    JOB_STATUS_NORMAL_TERMINATION = "nor"
    JOB_STATUS_ERROR_TERMINATION = "err"
    JOB_STATUS_OTHER_TERMINATION = "oth"
    JOB_STATUS_CHOICES = (
        (JOB_STATUS_NONE, "none / undefined"),
        (JOB_STATUS_PENDING, "pending"),
        (JOB_STATUS_RUNNING, "running"),
        (JOB_STATUS_FINISHED, "finished"),
        (JOB_STATUS_NORMAL_TERMINATION, "normal termination"),
        (JOB_STATUS_ERROR_TERMINATION, "error termination"),
        (JOB_STATUS_OTHER_TERMINATION, "other termination"),
    )
    job_status = models.CharField(
        max_length=3,
        choices=JOB_STATUS_CHOICES,
        blank=False
    )

    @property
    def _keyword_parsed_job_status(self):
        status_string = self.get_job_status_display()
        status_string = status_string.replace("/", "")
        return " ".join(status_string.split())

    job_dir = models.CharField(
        max_length=500,
        blank=True,
        null=True
    )

    sub_date = models.DateTimeField(
        default=timezone.now,
        blank=True
    )

    @property
    def sub_date_isostring(self):
        sub_date_date = date(
            year=self.sub_date.year,
            month=self.sub_date.month,
            day=self.sub_date.day,
        )
        return sub_date_date.isoformat()

    sub_dir = models.CharField(
        max_length=500,
        blank=False,
    )

    @property
    def _keyword_parsed_sub_dir(self):
        """
        Return parsed `sub_dir` string

        The parsing replaced the directory separating slashes `/`. Also, each
        folder name is contained once without out further modification and once
        each word of the folder names (words are separated by underscores) is
        contained in the `_keyword_parsed_sub_dir`.
        """
        split_at_slashes = self.sub_dir.split("/")
        parsed_words = set()
        for folder_name in split_at_slashes:
            parsed_words.add(folder_name)
            if "_" in folder_name:
                for word in folder_name.split("_"):
                    parsed_words.add(word)
        return " ".join(parsed_words)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    project = models.CharField(
        max_length=10,
        blank=True,
        null=True
    )

    solver = models.CharField(
        max_length=10,
        blank=True
    )

    logfile_path = models.CharField(
        max_length=200,
        blank=True
    )

    readme_filename = models.CharField(
        max_length=200,
        blank=True
    )

    # -------------------------------------------------------------------------
    # User information, open for editing
    # -------------------------------------------------------------------------
    info = models.TextField(
        blank=True,
    )

    # A job can have many base runs and each job can be a base run of many jobs
    # -> Many to many
    base_runs = models.ManyToManyField(
        "self",
        blank=True,
        symmetrical=False
        # null=True
    )

    ANALYSIS_STATUS_OPEN = "opn"
    ANALYSIS_STATUS_ONGOING = "ong"
    ANALYSIS_STATUS_DONE = "don"
    ANALYSIS_STATUS_CHOICES = (
        (ANALYSIS_STATUS_OPEN, "open"),
        (ANALYSIS_STATUS_ONGOING, "ongoing"),
        (ANALYSIS_STATUS_DONE, "done"),
    )
    analysis_status = models.CharField(
        max_length=3,
        choices=ANALYSIS_STATUS_CHOICES,
        blank=False,
        default=ANALYSIS_STATUS_OPEN
    )

    RESULT_ASSESSMENT_OK = "ok"
    RESULT_ASSESSMENT_NOK = "nok"
    RESULT_ASSESSMENT_OTHER = "oth"
    RESULT_ASSESSMENT_ISSUE = "isu"
    RESULT_ASSESSMENT_OBSOLETE = "obs"
    RESULT_ASSESSMENT_CHOICES = (
        (RESULT_ASSESSMENT_OK, "ok"),
        (RESULT_ASSESSMENT_NOK, "not ok"),
        (RESULT_ASSESSMENT_OTHER, "other"),
        (RESULT_ASSESSMENT_ISSUE, "issue"),
        (RESULT_ASSESSMENT_OBSOLETE, "obsolete"),
    )
    result_assessment = models.CharField(
        max_length=3,
        choices=RESULT_ASSESSMENT_CHOICES,
        blank=True
    )

    @property
    def _keyword_parsed_result_assessment(self):
        """
        Return keyword parsed result assessment

        The parsing adds the abbreviated form `nok` for to the `not ok`
        assessment display string. This is, because that is a common form and
        should allow the job to be search with one word instead of two.
        """
        display_string = self.get_result_assessment_display()
        if display_string == "not ok":
            display_string += " nok"
        return display_string

    result_summary = models.TextField(
        blank=True,
    )

    # -------------------------------------------------------------------------
    # Database/Admin info
    # -------------------------------------------------------------------------
    created = models.DateTimeField(
        default=timezone.now,
    )

    updated = models.DateTimeField(
        default=timezone.now,
    )

    # -------------------------------------------------------------------------
    # Search
    # -------------------------------------------------------------------------
    @staticmethod
    def _keyword_parse_fulltext(fulltext_string):
        """
        Return parsed version of input string

        Some fields (like `info` or `result_summary`) might contain longer
        texts with full sentences. The punctuation of these "fulltext" fields
        should be ignored during search.
        This functions can be used to parse these fulltext fields to make them
        more useful for search. The punctuation `()[]{}!?,."':;-_`
        in the beginning or end of a word is removed.

        Punctuation in the middle of a word is maintained. Words are separated
        by spaces " ".

        The returned string will only contain each word once. Duplicates are
        removed.

        This is implemented as a static method so that it will not receive an
        implicit first argument (`self`). This is important when the function
        is called inside the class via `self._keyword_parse_fulltext(args)`.
        See: https://docs.python.org/3.7/library/functions.html?highlight=stat
        icmethod#staticmethod
        """
        parsed_words = set()
        for word in fulltext_string.split():
            parsed_words.add(word.strip("()[]\{\}!?,.\"':;-_"))
        return " ".join(parsed_words)

    def _build_keyword_string(self):
        """
        Build a string of unique keywords describing the job

        The returned string contains whitespace separated words that help
        identify the job, e.g. to make it searchable.
        """
        unique_keywords = set()
        unique_keywords.add(str(self.job_id))
        unique_keywords.add(self.main_name)
        for word in self._keyword_parsed_main_name.split():
            unique_keywords.add(word)
        if self.user:
            unique_keywords.add(self.user.username)
        if self.project:
            unique_keywords.add(self.project)
        for word in self._keyword_parsed_sub_dir.split():
            unique_keywords.add(word)
        for word in self._keyword_parse_fulltext(self.info).split():
            unique_keywords.add(word)

diary/forms.py
"""
Module defining the forms for the CAE Job Diary application.
"""
from django.forms import ModelForm

from .models import Job


class JobForm(ModelForm):
    class Meta:
        model = Job
        fields = [
            "job_status",
            "job_dir",
            "info",
            "analysis_status",
            "result_assessment",
            "result_summary"
        ]

diary/views.py
import logging

from django.contrib import messages
from django.contrib.auth.models import User
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse, HttpResponseRedirect, QueryDict
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, TemplateView

from diary.models import Job
from diary.forms import JobForm


class JobListView(ListView):
    logger = logging.getLogger(__name__)

    # Which model does the view deal with
    model = Job
    # Which template should be used to render the view
    template_name = "diary/joblist.html"
    # Define the name with which the template can reference the queryset
    context_object_name = "jobs_list"

    def get_queryset(self):
        self.logger.debug("JobListView.get_queryset called.")

        jobs_list = Job.objects.order_by("-job_id")

        # Exclude obsolete jobs if not otherwise defined per query parameter
        self.show_obsolete = "show_obsolete" in self.request.GET
        self.logger.debug(f"Show obsolete: {self.show_obsolete}")
        if not self.show_obsolete:
            jobs_list = jobs_list.exclude(
                result_assessment=Job.RESULT_ASSESSMENT_OBSOLETE
            )

        # Apply filters if they where defined in the URL
        self.current_project_filter = self.request.GET.get("project")
        self.current_user_filter = self.request.GET.get("user")
        if self.current_project_filter:
            jobs_list = jobs_list.filter(project=self.current_project_filter)
        if self.current_user_filter:
            jobs_list = jobs_list.filter(
                user__username=self.current_user_filter)

        # Apply search query
        self.search_query = self.request.GET.get("q")
        self.logger.debug(f"Search query: {self.search_query}")
        if self.search_query is not None:
            # Stripping whitespaces from string to make whitespace search same
            # as empty one.
            self.search_query = self.search_query.strip()
        # A falsey (empty search) bypasses the actual search
        if self.search_query:
            jobs_list = jobs_list.keyword_search(self.search_query)

        paginated_jobs_list = Paginator(jobs_list, 25)
        page_number = self.request.GET.get("page")
        page_of_jobs = paginated_jobs_list.get_page(page_number)

        return page_of_jobs

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Get all users, but not the superusers
        context["usernames"] = \
            User.objects.all().filter(is_superuser=False).values_list(
                'username', flat=True).distinct().order_by('username')
        context["current_user_filter"] = self.current_user_filter
        # Get list of projects. This needs to be done via the jobs, because
        # there is no project model.
        context["projects"] = Job.objects.exclude(project="").values_list(
            'project', flat=True).distinct().order_by('project')
        context["current_project_filter"] = self.current_project_filter
        # Pass on the used search query
        context["current_search_query"] = self.search_query
        # Pass on the showing of obsolete jobs
        context["show_obsolete"] = self.show_obsolete
        return context


def detail(request, job_id):
    """Django view to show detailed information about a job from the DB

    Queries the defined job_id from the database and returns all
    available information rendered in the associated template.

    Parameters
    ----------
    job_id : int
        Job id of the job the detail view is desired for.
    """
    logger = logging.getLogger(__name__)
    logger.debug("detail() function called. Request: {}".format(request))

    if request.method == "POST":
        logger.debug("POST request received.")
        job = get_object_or_404(Job, pk=job_id)
        form = JobForm(request.POST, instance=job)
        if form.is_valid():
            logger.debug("Form is valid")
            form.save()
            # Define session value for update success
            logger.debug(f"Job update successful! Defining session parameter.")
            request.session["update_success"] = True
        else:
            logger.error(form.errors)

        # If a querystring was present in the POST action URL, this should be
        # passed on the next GET
        querystring = request.GET.urlencode()
        if querystring:
            querystring = "?" + querystring

        return HttpResponseRedirect(
            reverse("diary:detail",
                    kwargs={
                        "job_id": job_id
                    }) + querystring
        )
    else:
        job = get_object_or_404(Job, pk=job_id)
        form = JobForm(instance=job)

        # Check if the form has been used successfully to update the Job
        update_success = request.session.pop("update_success", False)
        logger.debug(f"Update successful: {update_success}")

        context = {
            "job": job,
            "form": form,
            "update_success": update_success
        }
        return render(request, "diary/detail.html", context)


class AboutView(TemplateView):
    template_name = "diary/about.html"

diary/templates/diary/about.html
{% extends "diary/base.html"%}
{% block title %}
About |
{% endblock %}
{% block page_title %}About{% endblock %}
{% block content %}
	<h5 id="help">Help</h5>
	<ul>
		<li>Obsolete Jobs 
			<p>
			Obsolete jobs (such with a result assessment set to "obsolete") are hidden from the job list by default.
			It is still possible to access the detail page of that job via it's job id in the URL (e.g. <code>/1234567/</code>).
			To show obsolete jobs in the job list, add <code>/?show_obsolete</code> to the URL like <a href="{% url "diary:joblist" %}?show_obsolete" >this</a>.
			If there are other query parameters present in the URL, the <code>show_obsolete</code> option can be chained via <code>&amp;</code> like <a href="{% url "diary:joblist" %}?q=main&amp;user=&amp;project=&amp;show_obsolete">this</a>.
			</p>
		</li>
	</ul>
	<h5 id="contributions">Contributions</h5>
	This page was build with contributions by the following people or materials from the following sources:
	<ul>
		<li>Icons made by <a href="https://www.flaticon.com/authors/dave-gandy" title="Dave Gandy">Dave Gandy</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> are licensed under <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></li>
		<li>Banner includes the font <a href="https://fonts.google.com/specimen/Amatic+SC">Amatic SC</a> by Vernon Adams and others which is licensed under <a href="https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&amp;id=OFL_web">Open Font License</a></li>
		<li>Main font of the page is <a href="https://fonts.google.com/specimen/Open+Sans">Open Sans</a> by Steve Matteson which is licensed under <a href="https://www.apache.org/licenses/LICENSE-2.0">Apache License, Version 2.0</a></li>
		<li>DOM manipulation on the page is powered by <a href="https://jquery.com/">jQuery</a> which is licensed under <a href="https://jquery.org/license/">The MIT License</a></li>
		<li>Styling of the page relies on <a href="https://getbootstrap.com/">Bootstrap</a> which is licensed under <a href="https://github.com/twbs/bootstrap/blob/v4.3.1/LICENSE">The MIT License</a></li>
	</ul>
{% endblock %}

diary/templates/diary/base.html
{% load static %}
{% load feedback_email %}
<!DOCTYPE html>
<html lang="en">
<head>
	{# meta #}
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	{# style #}
	<link rel="stylesheet" href="{% static 'bootstrap-4.3.1-dist/css/bootstrap.min.css' %}">
	<link rel="shortcut icon" href="{% static 'diary/img/caejd_logo_32.png' %}">
	<link rel="stylesheet" href="{% static 'diary/css/base.css' %}">
	{# script #}
	<script src="{% static 'jquery/jquery-3.3.1.min.js' %}" crossorigin="anonymous"></script>
	<script src="{% static 'bootstrap-4.3.1-dist/js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
	<script src="{% static 'diary/js/feedback.js' %}"></script>
	{# other #}
	<title>{% block title %}{% endblock %}CAE Job Diary</title>
	{% block head %}
	{% endblock %}
</head>
<body class="bg-light">
	<div id="feedback-modal" class="modal fade" tabindex="-1" role="dialog">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header align-items-center">
					<h5 class="modal-title">Give Feedback</h5>
					<button type="button" class="close" data-dismiss="modal">
						<span>&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<p>Just mail your feedback to the following email address:</p>
					<div class="input-group input-group-sm mb-3">
						<input type="text" class="form-control form-control-sm feedback-modal-email-display" name="feedback-email" value="{% get_feedback_email %}" >
						<div class="input-group-append" id="button-addon3">
							<a id="feedback-email-link" class="btn btn-light input-group-text" href="mailto:{% get_feedback_email %}?subject=Bug:&amp;body=Please add URL and a description of the bug:" data-toggle="tooltip" title="Send email">
								<img class="button-icon" src="{% static 'diary/img/envelope-of-white-paper.svg' %}">
							</a>
							<button id="feedback-email-copy-button" type="button" class="btn btn-light input-group-text" data-toggle="tooltip" title="Copy email address">
								<img class="button-icon" src="{% static 'diary/img/copy-document.svg' %}">
							</button>
						</div>
					</div>
					<p class="mb-0">You can style the email with <a href="https://gitlab.com/help/user/markdown" target="_blank">Markdown</a>.</p>
				</div>
			</div>
		</div>
	</div>
	<header class="sticky-top mb-3 border-bottom shadow-sm">
		<nav class="navbar navbar-expand navbar-light bg-light border-bottom">
				<a class="navbar-brand" href="{% url "diary:joblist" %}">
					<img src="{% static 'diary/img/banner.svg' %}" height="42">
				</a>
				<div class="navbar-nav ml-auto">
					<a class="nav-item nav-link" href="{% url "diary:joblist" %}">Job List</a>
					<a class="nav-item nav-link" href="{% url "diary:about" %}">About</a>
					<a class="nav-item nav-link" href="#" data-toggle="modal" data-target="#feedback-modal">Give Feedback</a>
				</div>
		</nav>
		<div class="container-fluid">
			<div class="row py-2 bg-light" style="min-height: 50px;">
				<div class="col-12 h4 my-0 d-flex flex-row text-nowrap align-items-center justify-content-between">
					{% block page_title %}{% endblock %}
					{% block page_header_content %}{% endblock %}
				</div>
			</div>
		</div>
	</header>
	{# Fixed top position is used, because IE11 is not supporting sticky #}
	{# Margin top of container needs to be adjusted to header sizing #}
	<div class="container-fluid">
		<div class="row">
			<main class="col">
			{% block content %}
			{% endblock %}
			</main>
		</div>
	</div>
</body>
</html>

diary/templates/diary/detail.html
{% extends "diary/base.html"%}
{% load static %}
{% load verbose_names %}
{% load request_querystring %}
{% load status_to_bootstrap_color %}
{% block head %}
	<link rel="stylesheet" href="{% static 'diary/css/detail.css' %}">
	<script src="{% static 'diary/js/detail.js' %}"></script>
{% endblock %}
{% block title %}
Job {{ job.job_id }} |
{% endblock %}
{% block page_title %}
<span class="text-truncate">
	<span class="badge badge badge-primary">{{ job.job_id }}</span><span class="px-2">{{ job.main_name }}</span>
</span>
{% endblock %}
{% block page_header_content %}
<div class="d-flex align-items-center justify-content-end text-nowrap">
	<a class="btn btn-outline-dark btn-sm" href="{% url "diary:joblist" %}{% get_full_querystring request %}">&#8676 Back to Job List</a>
</div>
{% endblock %}
{% block content %}
	{% if update_success %}
		<div id="changes-success" class="alert alert-success alert-dismissible fade show" role="alert">
			Changes successfully saved!
			<button type="button" class="close" data-dismiss="alert">
				<span>&times;</span>
			</button>
		</div>
	{% endif%}
	<div id="unsaved-changes-msg" class="alert alert-info" role="alert" style="display: none">You have unsaved changes!</div>
	<div class="card shadow-sm mb-3">
		<div class="row no-gutters">
			<div class="col-9">
				<div class="card-body">
					<form id="detail-form" action="{% url "diary:detail" job.job_id %}{% get_full_querystring request %}" method="post">
						<!--
						The current detail page might have a querystring if it was linked to by a filtered index.
						That querystring needs to be passed through, even if the form is submitted, because the form 
						redirects to the same detail view. 
						The whole point is to be able to get back to the filtered index view, even after the form was
						submitted.
						The current querystring is added to the action URL.
						 -->
						{% csrf_token %}
						<div class="row">
							<div class="col">
								<div class="form-group">
									{{ form.job_status.errors }}
									<label for="{{ form.job_status.id_for_label }}" class="text-muted">{{ form.job_status.label | title }}</label>
									<select id="{{ form.job_status.id_for_label }}" class="custom-select" name="{{ form.job_status.html_name }}">
										{% for choice in  form.job_status.field.choices %}
										<option value="{{ choice.0 }}" {% if choice.0 == form.job_status.value %}selected{% endif %}>{{ choice.1 }}</option>
										{% endfor %}
									</select>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-12 col-sm-6">
								<div class="form-group">
									{{ form.info.errors }}
									<label for="{{ form.info.id_for_label }}" class="text-muted">{{ form.info.label | title }}</label>
									<textarea id="{{ form.info.id_for_label }}" class="form-control" name="{{ form.info.html_name }}" rows="10">{{ form.info.value }}</textarea>
								</div>
							</div>
							<div class="col-12  col-sm-6">
								<div class="form-group">
									{{ form.result_summary.errors }}
									<label for="{{ form.result_summary.id_for_label }}" class="text-muted">{{ form.result_summary.label | title }}</label>
									<textarea id="{{ form.result_summary.id_for_label }}" class="form-control" name="{{ form.result_summary.html_name }}" rows="10">{{ form.result_summary.value }}</textarea>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-12 col-sm-6">
								<div class="form-group">
									{{ form.analysis_status.errors }}
									<label for="{{ form.analysis_status.id_for_label }}" class="text-muted">{{ form.analysis_status.label | title }}</label>
									<select id="{{ form.analysis_status.id_for_label }}" class="custom-select" name="{{ form.analysis_status.html_name }}">
										{% for choice in  form.analysis_status.field.choices %}
										<option value="{{ choice.0 }}" {% if choice.0 == form.analysis_status.value %}selected{% endif %}>{{ choice.1 }}</option>
										{% endfor %}
									</select>
								</div>
							</div>
							<div class="col-12 col-sm-6">
								<div class="form-group">
									{{ form.result_assessment.errors }}
									<label for="{{ form.result_assessment.id_for_label }}" class="text-muted">{{ form.result_assessment.label | title }}</label>
									<select id="{{ form.result_assessment.id_for_label }}" class="custom-select" name="{{ form.result_assessment.html_name }}">
										{% for choice in  form.result_assessment.field.choices %}
										<option value="{{ choice.0 }}" {% if choice.0 == form.result_assessment.value %}selected{% endif %}>{{ choice.1 }}</option>
										{% endfor %}
									</select>
								</div>
							</div>
							<div class="col-12">
								<div id="obsolete_warning" class="alert alert-warning" role="alert" style="display: none">
									Attention! "Obsolete" jobs are hidden from the job list by default! <br>
									To show obsolete jobs in the job list, add <code>?show_obsolete</code> to the URL.<br>
									For more information see the <a href="{% url "diary:about" %}#help" target="_blank" class="alert-link">help section</a> on the "About" page.
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col d-flex justify-content-between">
								<input type="submit" class="btn btn-success" value="Save Changes">
								<input id="reset-button" class="btn btn-link" type="reset" value="Reset">
							</div>
						</div>
					</form>
				</div>
			</div>
			<div class="col-3 border-left">
				<ul class="list-group list-group-flush">
					<li class="list-group-item">
						<label for="job_id" class="text-muted small mb-0">{% get_verbose_field_name job "job_id" %}</label>
						<div id="job_id">{{ job.job_id }}</div>
					</li>
					<li class="list-group-item">
						<label for="main_name" class="text-muted small mb-0">{% get_verbose_field_name job "main_name" %}</label>
						<div id="main_name">{{ job.main_name }}</div>
					</li>
					<li class="list-group-item">
						<label for="job_status" class="text-muted small mb-0">{% get_verbose_field_name job "job_status" %}</label>
						<div id="job_status"><span class="badge badge-pill badge-{% job_status_to_color job.job_status %}">{{ job.get_job_status_display }}</span></div>
					</li>
					<li class="list-group-item">
						<label for="project" class="text-muted small mb-0">{% get_verbose_field_name job "project" %}</label>
						<div class="project"><a href="{% url 'diary:joblist' %}?project={{ job.project }}">{{ job.project }}</a></div>
					</li>
					<li class="list-group-item">
						<label for="user" class="text-muted small mb-0">{% get_verbose_field_name job "user" %}</label>
						<div id="user"><a href="{% url 'diary:joblist' %}?user={{ job.user }}">{{ job.user }}</a></div>
					</li>
					<li class="list-group-item">
						<label for="base_runs" class="text-muted small mb-0">{% get_verbose_field_name job "base_runs" %}</label>
						<div id="base_runs">
							{% for base_run in job.base_runs.all %}
								<a href="{% url "diary:detail" job_id=base_run.job_id %}" class="badge badge-secondary">{{ base_run.job_id}}</a>
							{% endfor %}
						</div>
					</li>
					<li class="list-group-item">
						<label for="sub_dir" class="text-muted small mb-0">{% get_verbose_field_name job "sub_dir" %}</label>
						<div id="sub_dir">{{ job.sub_dir }}</div>
					</li>
					<li class="list-group-item">
						<label for="job_dir" class="text-muted small mb-0">{% get_verbose_field_name job "job_dir" %}</label>
						<div id="job_dir">{{ job.job_dir }}</div>
					</li>
					<li class="list-group-item">
						<label for="sub_date" class="text-muted small mb-0">{% get_verbose_field_name job "sub_date" %}</label>
						<div id="sub_date">{{ job.sub_date }}</div>
					</li>
				</ul>
			</div>
		</div>
	</div>
{% endblock %}